/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallbackClientRouteImport } from './routes/callback-client'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as FormStudioRouteImport } from './routes/form/$studio'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardClientsRouteImport } from './routes/dashboard/clients'

const CallbackClientRoute = CallbackClientRouteImport.update({
  id: '/callback-client',
  path: '/callback-client',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const FormStudioRoute = FormStudioRouteImport.update({
  id: '/form/$studio',
  path: '/form/$studio',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/callback-client': typeof CallbackClientRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/form/$studio': typeof FormStudioRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/callback-client': typeof CallbackClientRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/form/$studio': typeof FormStudioRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/callback-client': typeof CallbackClientRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/form/$studio': typeof FormStudioRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/callback-client'
    | '/dashboard/clients'
    | '/dashboard/settings'
    | '/form/$studio'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback-client'
    | '/dashboard/clients'
    | '/dashboard/settings'
    | '/form/$studio'
    | '/dashboard'
  id:
    | '__root__'
    | '/dashboard'
    | '/callback-client'
    | '/dashboard/clients'
    | '/dashboard/settings'
    | '/form/$studio'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  CallbackClientRoute: typeof CallbackClientRoute
  FormStudioRoute: typeof FormStudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/callback-client': {
      id: '/callback-client'
      path: '/callback-client'
      fullPath: '/callback-client'
      preLoaderRoute: typeof CallbackClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/form/$studio': {
      id: '/form/$studio'
      path: '/form/$studio'
      fullPath: '/form/$studio'
      preLoaderRoute: typeof FormStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  CallbackClientRoute: CallbackClientRoute,
  FormStudioRoute: FormStudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
